2015-10-16 12:43:49
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/sftp_transport.py", line 354, in get
  File "./sftp/file_transfer.py", line 328, in handle_get_dirs
  File "./sftp/sftp_transport.py", line 324, in lcd
NotFoundError: Folder not found
